### PR TITLE
removed more functions without any effect

### PR DESCRIPTION
**Pull request by df8oe**
and added possibility of changing RTTY shift. Many thanks for your help.

### CODE REVIEW

**Review by Qyon — CHANGES_REQUESTED** [review]
I think, that "// WARNING: do not use this in flying tracker!" should be leaved in config.h - it would be pitty if sonde decides to switch off 7km above the ground :)

**Comment by df8oe** [comment]
You have right from a specific view - but:

- original Vaisala sonde always can be switched off by a VERY SHORT press of this button (and never stops working during flight because of button is pressed)
- our implementation ignores short pressings of the button. You have to press it for seconds. This reduces errors again.
- plastic case of sonde has design that shocks never can press button by accident

I do not see any advantage in disabling the button during a flight...

**Comment by Qyon** [comment]
You forget, that this is ADC input, and I personaly expirienced some quirks
before...

**Comment by df8oe** [comment]
OK. I added comment. Of course it is a good idea to take a look again at the power-off routines to make them more robust. This cannot be a problem because Vaisala does not fear accidently powering off of sonde during flight.

**Comment by df8oe** [comment]
Hi,
because of project is much better to find I renamed project name and changed files containing these informations. Maybe at a later stage it would be a good idea to rename the whole project on GitHub - but at this time it is not neccessary (and I would discuss that with you if I plan to change GitHub repo name). If we want to be successful in our TODOs it would be great if there is much more contribution - and I think we will get them if project has a well-known name :)

**Comment by df8oe** [comment]
Can you / will you maintain CoIDE support? I cannot do this because I do not use Windows... I am working at another C project which originally was build using CoIDE. Because of the future of CooCox is unsecure we decided to add support for EmBITZ, which is an IDE as simple as CoIDE. Can you think about to add support for this IDE, too? I will start Eclipse support in future (it is platform independent and has mighty debug features which neither CoIDE nor EmBITZ do have...)

**Comment by Qyon** [comment]
I will maintain CoIDE support.

**Review by Qyon — APPROVED** [review]

**Comment by Qyon** [comment]
Did you merged my repo before making pull request? Because there were some conflicts to resolve.

**Comment by df8oe** [comment]
Yes - I have had done this (so I thought). But maybe I have misspelled something here so that I have fetched it but forgotten to merge  - sorry...

**Comment by 9a9y** [comment]
You have right about button, till now I have never found sonde on which button caused to stop working.
Low voltage in battery make that sonde stop working. I have lot of time push button ON and sonde start working but with lower output power.

**Pull request merged**
