### PR TITLE
hopefully fixed broken APRS

### PR DESCRIPTION
**Pull request by df8oe**
I cannot test actually APRS so please confirm if it is working now

### CODE REVIEW

**Comment by 9a9y** [comment]
I test today and let you know. Little later. 73

**Comment by Qyon** [comment]
Thanks. Best wishes front Tama 2017 - Polish APRS meeting

16.06.2017 12:14 PM "9a9y" <notifications@github.com> napisał(a):

**Comment by df8oe** [comment]
REQUEST:
It would be great if polish comments can be changed (or additionaly provided) english comments. I am not familar with polish language and it is hard to use google translate every time e.g. I want to understand QAPRS code :) Maybe there is potential for optimizations which reduce CPU load. Not very high priority - but nice2have...

**Comment by Qyon** [comment]
If I have time I will try to add English comments this week.

**Pull request merged**
