### PR TITLE
some refactorings, removed unused functions and files, added license text of GPL v2

### PR DESCRIPTION
**Pull request by df8oe**

### CODE REVIEW

**Review by Qyon — APPROVED** [review]
Thankf for your work

**Comment by Qyon** [comment]
Could you explain how You get TX_POWER power values?

**Comment by df8oe** [comment]
This information is extracted out of the datasheet specs of the radio chip. Please take a look at register descriptions in docs folder at page 30. The values are matching reality power very good.

**Comment by Qyon** [comment]
Page 32 in
https://www.silabs.com/documents/public/data-sheets/Si4030-31-32.pdf says
that max Si4032 output power is 20dBm, which roughly corresponds with my
measurements done on Agilent E4406A (42.95mW/16.33dBm, probably due to not
perfect matching on 432MHz).

**Pull request merged**
