### PR TITLE
Adding Linux support for cmake, making rtty greeting line more comfortable editable

### PR DESCRIPTION
**Pull request by df8oe**

### CODE REVIEW

**Review by Qyon — COMMENTED** [review]
This code is unused

**Comment by df8oe** [comment]
OK - I see. I roll back and start a new pr if neccessary.

**Comment by 9a9y** [comment]
Thank you for good change in code.
All work perfect with APRS and RTTY.
I have try some experiment for reading sensors... but till now no luck. Too much complex.

**Comment by df8oe** [comment]
Maybe it is a good idea to share the things we already found out? I do not have dig much deep into the hardware but as I can see there is no interface chip controlling temp and hum sensor - they are applied to STM directly, isn't it? I saw an analogue switch (4 stages): does this switch sensors? If we work together we can work it out - I am nearly sure.

**Comment by 9a9y** [comment]
Same opinion, values from sensors goes to STM.
I also know that one input is for ozone sensor (very very rare used).
I am sure that all calculations for sensor values are in STM, if you broke temp or humidity sensor, sonde send error.
I have lot a play first with temp sensor, reading values of resistance on different temoeratures etc., but till now nothing found. Only have found that in humidity sensor goes voltage for heating sensor and then values goes to STM.
Maybe that something help.

**Comment by df8oe** [comment]
I have additional information about kind of temperature sensor. It is NOT by resistance, but by capacity. I think I must take measures using a sonde with original firmware. We should inform each other if we found out something new.

All sondes I have caught here contain pressure module. And every Thursday RS41 coupled with ozone sonde is launched from de Bilt. I do not have one yet - but it is only a question of time :)

73
Andreas

**Comment by 9a9y** [comment]
Thank's for info. I make also tests with original sonde. Changing temperature and measure capacity, maybe we come to any value. With humidity and pressure sensor I think that depends on voltage that go back to STM . 
We must make some test, I doo that, will be good that also someone else make so that we can compare results.
You have luck with ozone sensors, here in 9A it is very rare situation.

**Comment by df8oe** [comment]
I think I am a big step on the way to crack temperature sensor. I have added a new document to docs. Please test and confirm. If I am right we are only a few steps away from integrating temperature to telemetry :)

**Comment by 9a9y** [comment]
Just like I have measured and tested before, resistance... with change of temperature it change value of resistance.
You are on the right way.
Thank you for pinout, now I will see if I have right about humidity sensor... I suspect that he send voltage unit to STM with change of humidity... but we must check that.
Till now I do not have right pinout and that was problem with testing.

**Comment by df8oe** [comment]
I have done more investigations. I do not see any other ADC input is active except pin16. All others are used as normal digitally GPIOs. And voltage at pin16 does not change when I vary temperature resistor.

Pin4 and Pin 11 of sensor boom (temp / hum2) are going to an anlogue switch (YC751) which is used as multiplexer. Signal of temp sensor or hum2 sensor is switched to one signal which leads to a very small 8 pin chip named "Y34". There are going on very interesting things at the pins and it would help very much if we know what it is. Unfortunately I have not found any informations on the web. It can be an ADC, a voltage-2-frequency converter etc. Do you have informations here?

73
Andreas

**Comment by 9a9y** [comment]
I have measured resistance between pins 4 and 6 with change of temperature, resistance changed every time when temperature are changed and sonde go on TX.
27.5 C = 1,055 KOhm
27.6 C = 1,065 KOhm
27.7 C = 1,103 KOhm
28.1 C = 1,197 KOhm
It is very hard to measure because short TX time.
Now must try to measure other combinations of pins: to GND etc.

**Comment by df8oe** [comment]
It is differential. Not to GND or VCC

**Comment by df8oe** [comment]
I am stuck at the moment at "Y34" - so I decided to work on pressure sensor. It is connected to SPI2 - but not as "standard SPI device". It uses SPI_NSS and one dataline (from module to STM), other direction is not connected. Clock is used from SPI2. So I think it is a kind of polling. SPI2 is also connected to small extension header (for ozone device e.g.)

**Comment by df8oe** [comment]
I searched for "Y34" but no success at all. Near to this chip there is a 6 pin labeled "Z27B" (also no informations to find on the web). During measuring using my diode tester with integrated beeper (no power supply connected) I got an oscillation (audio sound with variable frequency) out of my diode tester so I am nearly sure around this parts there is a  voltage to frequency conversion done. Timing and reference frequencies are generated via STM. I am sure because of signals switching around in sensor area is only present with Vaisala firmware. If our HAM firmware is supplied all signals in sensor area are gone. So the main work will be to investigate which signals come out of what GPIO of STM - and where are they used for :/ Much 2do I feel. My first idea is to desolder STM and see what pins are not connected for reducing points we must investigate. Do you have done that already?

73
Andreas

**Pull request closed without merging**
